apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: plugin-ejwt
  namespace: kong-app
plugin: ejwt
config:
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: plugin-jwt
  namespace: kong-app
plugin: jwt
config:
